# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  workflow_dispatch:
    inputs:
      name: 
        type: choice
        description: Who to greet
        options: 
          - monalisa
          - cschleiden
      message:
          type: string
          required: true
      boolean:
        type: boolean
        description: True or False

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
  greet:
    runs-on: ubuntu-latest
    needs: build
    steps:
      
    - name: Send greeting
      run: |
        echo "boolean is ${{ github.event.inputs.boolean }}"
        echo "choice is ${{ github.event.inputs.choice }}"
        echo "Message is ${{ github.event.inputs.message }}"
